# Generated by Django 2.2.4 on 2019-09-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bsc_chem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='bsc_it',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='bsc_maths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='bsc_phys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='civil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='etc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='mecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='msc_chem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='msc_maths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='msc_phys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='pei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=15)),
            ],
        ),
    ]
