# Generated by Django 2.2.4 on 2019-09-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='pei',
        ),
        migrations.AlterField(
            model_name='bsc_chem',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bsc_it',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bsc_maths',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bsc_phys',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='civil',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etc',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mecha',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='msc_chem',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='msc_maths',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='msc_phys',
            name='number',
            field=models.IntegerField(),
        ),
    ]
