# Generated by Django 2.2.4 on 2019-09-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190906_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bsc_chem',
            new_name='Chem',
        ),
        migrations.RenameModel(
            old_name='bsc_phys',
            new_name='It',
        ),
        migrations.RenameModel(
            old_name='bsc_maths',
            new_name='Maths',
        ),
        migrations.RenameModel(
            old_name='msc_phys',
            new_name='Phys',
        ),
        migrations.DeleteModel(
            name='bsc_it',
        ),
        migrations.DeleteModel(
            name='msc_chem',
        ),
        migrations.DeleteModel(
            name='msc_maths',
        ),
    ]
