# Generated by Django 2.2.4 on 2019-09-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190914_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
    ]
