# Generated by Django 2.2.4 on 2019-09-16 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_feedback_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
