# Generated by Django 2.2.4 on 2019-09-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('father_name', models.CharField(max_length=25)),
                ('mother_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=6)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
