# Generated by Django 2.2.4 on 2019-09-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.IntegerField(default='000'),
        ),
    ]
