# Generated by Django 2.2.4 on 2019-09-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_student_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='code',
            new_name='student_code',
        ),
    ]
