# Generated by Django 2.2.4 on 2019-10-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20191005_0254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accounts',
            new_name='Account',
        ),
    ]
