# Generated by Django 2.2.4 on 2019-10-08 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20191005_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='notice',
            name='files',
            field=models.ImageField(default='', upload_to='notice/files'),
        ),
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(default='', upload_to='notice/images'),
        ),
    ]
