# Generated by Django 2.2.4 on 2019-10-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20191008_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='image',
        ),
    ]
