# Generated by Django 2.2.4 on 2019-10-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20191008_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='images',
            field=models.FileField(blank=True, default='', null=True, upload_to='notice/images/'),
        ),
    ]
