# Generated by Django 2.2.4 on 2019-10-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_notice_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='files',
            new_name='pdf',
        ),
    ]
