# Generated by Django 2.2.4 on 2019-10-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20191008_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='desc',
            new_name='notice',
        ),
    ]
