# Generated by Django 2.2.4 on 2019-11-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_feedback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_code',
        ),
    ]
